apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-microservice
  labels:
    app: eks-microservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: eks-microservice
  template:
    metadata:
      labels:
        app: eks-microservice
    spec:
      containers:
      - name: eks-microservice
        image: 053483219622.dkr.ecr.us-east-1.amazonaws.com/eks-test/web/prod:a327ca1e
        ports:
        - containerPort: 8000
          name: http-server
